
## roles/cryptogen/tasks/main/yml
## 
## This role is for fabric-ca host
## 
## host fabric-ca has certs from ca and can generate common cryptomaterial
## 
## TODO - repalce by using industrial keys and CAs

- name: translate crypto template for cryptogen
  template:
    src: "files/crypto-config.yml.j2"
    dest: "{{ binary_dir }}crypto-config.yml"
    backup: yes
  become: no


- name: generate ctyptomaterial using config
  shell: cryptogen generate --config=crypto-config.yml 
  args:
    chdir: {{ binary_dir }}
  become: no



- name: distribute cryptomaterial all over the hardware hosts
  copy:







