
## roles/cryptogen/tasks/main/yml



## we use ctyptogen binary tool for stand but it is neccessary to use accurate security policy for real implements

- name: translate crypto template
  template:
    src: "files/crypto-config.yml.j2"
    dest: "{{ binary_dir }}crypto-config.yml"
    backup: yes
  become: no

## we need to generate keys 