
## roles/cryptogen/tasks/main/yml
## 
## This role is for fabric-ca host  - we using openssl and fabric-ca server
## 
## host fabric-ca has certs from ca and can generate common cryptomaterial
## 
## TODO - repalce by using industrial keys and CAs
## TODO - list of OUs is one for organization!!!! 


---
- hosts: fabric-ca
  name: generate admin keys by subrole and distribute ca and admin keys to management machine
  include_role:
    name: "{{playbook_dir}}/../roles/subroles/cryptogen_admin_key"


- hosts: hv
  name: generate orderers signing keys and cryptomaterial


- hosts: hv
  name: generate peers signing keys and cryptomaterial


- hosts: hv
  name: distribute all serts (not keys) to all hosts for united local msp


  
#TODO - tls certs for ca, peers, orderers, operation servers