
## roles/cryptogen/tasks/main/yml
## 
## This role is for fabric-ca host  - we using openssl and fabric-ca server
## 
## host fabric-ca has certs from ca and can generate common cryptomaterial
## 
## TODO - repalce by using industrial keys and CAs


## we parse our cryprtogen
- name: cryptomaterial on fabric-ca-host for admins
  openssl_privatekey:
      path: "{{ keystore }}admin_sk.pem"
      size: 4096
      curve: secp256r1
      type: ECC
      force: yes
      # cipher: auto
      select_crypto_backend: cryptography
#TODO  - we are using cryptography

- name: cert from secret_key



 












