

---
- shell: mkdir -p '{{ fabric_dir }}' '{{ config_dir }}' '{{ binary_dir }}' '{{ msp_dir }}' '{{fabric_ca_dir }}'
  args:
    warn: no
  become: yes
   

- name: chmod for our dirs
  file:
    path: '{{ item }}'
    state: directory
    mode: 42775
    recurse: yes
   # owner: '{{ username }}'
  with_items:
    - '{{ fabric_dir }}'
    - '{{ binary_dir }}'     
    - '{{ msp_dir }}' 
    - '{{ config_dir }}'
    - '{{ fabric_ca_dir }}'
    #- '/usr/local/go'
  become: yes  


# tODO - fix go env from noroot to root context: PATH, GOPATH, GOROOT, GOMOD
  
#- name: save environ facts for future go build as root 
#  setup:
#  become: no

    

- name: generate cryptogen bin for hosts from src
  shell: "{{ item }}"
  args:
    chdir: "{{ fabric_src_dir }}"
  with_items:    
    - cd {{ fabric_src_dir }}
    - go mod init
    - go mod tidy
    - go build -o {{ fabric_src_dir }}cryptogen  {{ fabric_src_dir }}common/tools/cryptogen/main.go
    - cp {{ fabric_src_dir }}cryptogen {{ binary_dir }}
  become: no
  ignore_errors: True
  environment:
    PATH: /sbin:/usr/sbin:/bin:/usr/bin:/usr/local/bin:/usr/local/go/bin
    GOPATH: /home/laborant/go
    GOMOD: /home/laborant/fabric/go.mod
    GOROOT: /usr/local/go



- name: generate configtxgen bin for hosts from src
  shell: "{{ item }}"
  args:
    chdir: "{{ fabric_src_dir }}"
  with_items:  
    - go get github.com/hyperledger/fabric-ca 
    - cd {{ fabric_src_dir }}
    - go mod init
    - cd {{ fabric_src_dir }}
    - go build -o {{ fabric_src_dir }}configtxgen  {{ fabric_src_dir }}common/tools/cryptogen/main.go
    - cp {{ fabric_src_dir }}configtxgen {{ binary_dir }}
  become: no
  ignore_errors: True
  environment:
    PATH: /sbin:/usr/sbin:/bin:/usr/bin:/usr/local/bin:/usr/local/go/bin
    GOPATH: /home/laborant/go
    GOMOD: /home/laborant/fabric/go.mod
    GOROOT: /usr/local/go







