

---
#- shell: mkdir -p '{{ fabric_dir }}' '{{ config_dir }}' '{{ binary_dir }}' '{{ msp_dir }}'
#  args:
#    warn: no
#  become: yes
   

- name: create dirs
  file:
    path: '{{ item }}'
    state: directory
    mode: 40775
   # owner: '{{ username }}'
  with_items:
    - '{{ fabric_dir }}'
    - '{{ binary_dir }} '     
    - '{{ msp_dir }}'
    - '{{ config_dir }}'
  become: yes  



  

- name: generate cryptogen bin for hosts from src
  shell: "{{ item }}"
  args:
    chdir: "{{ fabric_src_dir }}"
  with_items:    
    
    - cd {{ fabric_src_dir }}
    - go mod init
   # - go mod vendor
   # - go mod tidy
    - cd {{ fabric_src_dir }}
    - go build -o {{ fabric_src_dir }}cryptogen -i {{ fabric_src_dir }}common/tools/cryptogen/main.go
    - cp {{ fabric_src_dir }}cryptogen {{ binary_dir }}
    - chmod 777 {{ binary_dir }}* 
  become: yes
  ignore_errors: True
  environment:
    PATH: /sbin:/usr/sbin:/bin:/usr/bin:/usr/local/bin:/usr/local/go/bin
    GOPATH: /home/laborant/go
    GOMOD: /home/laborant/fabric/go.mod
    GOROOT: /usr/local/go





#- name: Generate crypto-config templates
#  template:
#    src: 
#    dest: 
#    backup: yes
