- hosts: hv
  tasks:
  - name: copy repos
    copy:
     src: "{{ pathdir }}{{ src }}"
     dest: "/etc/apt"
     backup: yes
    become: yes

  - name: add repos from library
    shell: cat {{ src }} > sources.list
    args:
     chdir: /etc/apt/
    become: yes 
   





