
- hosts: hv
  vars_files:
     - "{{playbook_dir}}/../globalvars/global.yml"
  tasks:

  - name: clear 
    file: 
      path: "{{ item }}"
      state: absent
    with_items:
      - "{{ golang_dir }}"
      - "{{ fabric_src_dir }}"
      - "{{ fabric_dir }}"
      -  /usr/local/go
      -  "{{ fabric_ca_src_dir }}"
    become: yes

  
- hosts:  fabric_ca_host
  vars_files:
     - "{{playbook_dir}}/../globalvars/global.yml"
  tasks:

  - name: stop fabric-ca service
    ignore_errors: true
    systemd:
      name: fabric-ca-server
      state: stopped
      daemon_reload: yes
      enabled: yes
    become: yes    
    

    

  