

- name: " prepare HLF dependicies "
  gather_facts: yes
  hosts: hv
  
  vars_files:
     - "{{playbook_dir}}/../globalvars/global.yml"
  roles:
      - "{{playbook_dir}}/../roles/cryptogen"  
  tags:
    - "fabric ca role "     
       