

- name: " prepare HLF dependicies "
  gather_facts: yes
  hosts: hv
  
  vars_files:
     - "{{playbook_dir}}/../globalvars/global.yml"
  roles:
      - "{{playbook_dir}}/../roles/common"  
  tags:
    - "utility binary and configs buildings "     
       