## hostprep/tasks/main.yml - task for instaling all prerequisities for HLF fabric on target hosts
## TODO - roles logic by some config.yaml
- name: prepare hardware hosts
  become: no
  gather_facts: yes
  hosts: hv
  vars_files:
     - "{{playbook_dir}}/../globalvars/global.yml"
  roles:
    - role: "{{playbook_dir}}/../roles/hostprep"
  tags:
     - "hosts prepare"
  

- name: " prepare HLF dependicies "
  gather_facts: yes
  hosts: hv
  vars_files:
     - "{{playbook_dir}}/../globalvars/global.yml"
  roles:
      - "{{playbook_dir}}/../roles/common"  
  tags:
    - "utility binary and configs buildings " 


#optional.  At production ought to use own CA or carefuly protect our CAaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
- name: "generate and run fabric_ca server and client"
  gather_facts: no
  hosts: fabric_ca_host
  vars_files:
  - "{{playbook_dir}}/../globalvars/global.yml"
  roles:
     - "{{playbook_dir}}/../roles/fabric_ca"  
  tags: 
    - "fabric ca start"      


## private keys generating + CA key for signing 
- name: generate secret keys on management machine
  gather_facts: no
  hosts: localhost
  vars_files:
    - "{{playbook_dir}}/../globalvars/global.yml"
  roles:
    - "{{playbook_dir}}/../roles/cryptogen"  




- name: generate secret keys on management machine
  gather_facts: no
  hosts: hv
  vars_files:
    - "{{playbook_dir}}/../globalvars/global.yml"
  roles:
    - "{{playbook_dir}}/../roles/cryptogen"  


#optional.  At production ought to use certs for principals
- name: generate all cryptometrial 
  gather_facts: no
  hosts: hv
  vars_files:
    - "{{playbook_dir}}/../globalvars/global.yml"
  roles:
     - "{{playbook_dir}}/../roles/cryptogen"  
  tags: 
    - "fabric ca start"      


      
       