## hostprep/tasks/main.yml - task for instaling all prerequisities for HLF fabric on target hosts
## TODO - roles logic by some config.yaml
- name: prepare hardwre hosts
  become: no
  gather_facts: yes
  hosts: hv
  vars_files:
     - "{{playbook_dir}}/../globalvars/global.yml"
  roles:
    - role: "{{playbook_dir}}/../roles/hostprep"
  tags:
     - "hosts prepare"
  # when: from_zero == "true"

- name: " prepare HLF dependicies "
  gather_facts: yes
  hosts: hv
  vars_files:
     - "{{playbook_dir}}/../globalvars/global.yml"
  roles:
      - "{{playbook_dir}}/../roles/common"  
  tags:
    - "utility binary and configs buildings " 


- name: "generate fabric_ca server"
  gather_facts: no
  hosts: hv
  vars_files:
    - "{{playbook_dir}}/../globalvars/global.yml"
  roles:
     - "{{playbook_dir}}/../roles/fabric_ca"     


      
       