- hosts: hv
  
  vars_files:
     - "{{playbook_dir}}/../globalvars/global.yml"  
  
  tasks:
  - name: change permissions
    
    file:
      path: '{{ item }}'
      state: directory
      mode: 42775
      recurse: yes
      
   # owner: '{{ username }}'
    with_items:
    - '{{ fabric_dir }}'
    - '{{ binary_dir }} '     
    - '{{ msp_dir }}' 
    - '{{ config_dir }}'
    - '/usr/local/go'
    become: yes  

