#####  /roles/hostprep/tasks/main/yml 
#main of host prepare tasks
# we copy src and install from apt and src:  Curl, Docker,Docker-Compose, Fabric, golang

---

# TODO - make diffirent repos according to linux version or make in variables
-



- name: add apt repos
  apt_repository:
    repo: "{{ item }}"
    state: present
  with_items:
    - deb-src http://security.debian.org/debian-security/ buster/updates main
    - deb http://security.debian.org/debian-security/ buster/updates main
    - deb http://deb.debian.org/debian/ buster-backports main 
    - deb http://deb.debian.org/debian/ buster main 
  become: yes  
        

   
- name: repo maintance work 
  apt:
    update_cache: yes
    force: yes
    autoremove: yes
    purge: yes
    autoclean: yes
    allow_unauthenticated: yes
    #upgrade: yes
    #force_apt_get: yes
  become: yes


  


- name: "install prerequisities:  CURL, GIT, MC"
  apt:
    name: ['curl', 'mc', 'apt-transport-https', 'git', 'qemu', 'libtool' , 'libltdl-dev', 'htop', 'openssl', 'aptitude']
    state: latest
    force_apt_get: yes
  become: yes
  

- name: git config for fabric
  git_config:
    name: core.autocrlf
    scope: global
    value: "false"

- git_config:
    name: core.longpaths
    scope: global
    value: "true"    



- name: instal GO by role if curversion is not our
  include_role: 
    name: "{{playbook_dir}}/../roles/golang_install"
   

         
# TODO  - make Repo in variable and use local repos
- name: git
  git: 
    repo: 'https://github.com/hyperledger/fabric'
    dest:  "{{ fabric_src_dir }}"
    version: release-"{{ fabric_release }}"
  become: no



# TODO - make docker GPG surce in variable
- name: add repo and gpg key for docker install
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present  
  become: yes  


#-TODO - make docker repo in variable
- apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/debian buster stable"
    state: present
    update_cache: yes
  become: yes    
  
  
#- name: install docker repos
- apt:
    name: 
      - docker-ce
      - docker-ce-cli
      - containerd.io 
    state: latest
    force_apt_get: yes
  become: yes 


#- name: install docker composer by get_url + executable mode
- get_url:
    dest: /usr/local/bin/docker-compose
    url: https://github.com/docker/compose/releases/download/1.24.0/docker-compose-Linux-x86_64
    backup: no # not required. Create a backup file including the timestamp information so you can get the original file back if you somehow clobbered it incorrectly.
    force: no # not required. If C(yes) and C(dest) is not a directory, will download the file every time and replace the file if the contents change. If C(no), the file will only be downloaded if the destination does not exist. Generally should be C(yes) only for small local files.,Prior to 0.6, this module behaved as if C(yes) was the default.
    mode: 100755 
    attributes: 
  become: yes  



       




