# main of host prepare tasks
# we copy src and install from apt and src:  Curl, Docker,Docker-Compose, Fabric, golang

---
- name: create dir for ssh key
  file:
    path: "~/.ssh"
    state: directory
   

- name: copy public key to destination
  copy:
   src: "{{ pubkey }}"
   dest: ~/.ssh/
   #owner: "{{ username }}"
   mode: u=rw,g=r,o=rw
   backup: yes
    

- name: remote add key to authorized keys
  shell: cat {{ pubkey }} >> authorized_keys
  args:
    chdir: ~/.ssh/
        

   
- name: apt update cache
  apt:
    update_cache: yes
  become: yes
    

- name:  upgrade in scilence
  apt:
    name: "*"
    state: latest
  become: yes  
    


- name: "install prerequisities:  install CURL"
  apt:
    name: curl
    state: latest
  #become: yes
    


- name: "create dir for go"
  
  file:
    path: "~/go"
    state: directory
  become: no  
 
  
  
- name: copy go src
  copy:
    src: "{{ role_path }}/files/go.tar.gz"
    dest: "{{ golang_dir }}"
    #backup: yes
  become: no
  
- name: extract go  
  unarchive:  
    src: "{{ golang_dir }}/go.tar.gz"
    dest: "{{ golang_dir }}"
    remote_src: yes
  become: no  
    

    
  
  
  
- name: copy fabric src  
  copy:
    src: "{{ role_path }}/files/fab.tar"
    dest: "{{ fabric_src_dir}}"
    backup: yes
  #become: yes


